#%RAML 1.0 Library
types:
  success:
    description: A succesful (2xx) response body.
    type: object
    additionalProperties: false
    properties:
      data: data
      included?:
        type: resource[]
        description: To reduce the number of HTTP requests, servers **MAY** allow responses that include related resources along with the requested primary resources. Such responses are called "compound documents".
        uniqueItems: true
      meta?: meta
      links?:
        type: pagelinks
        description: Link members related to the primary data.
      jsonapi?: jsonapi
  failure:
    description: A failure (4xx) response body.
    additionalProperties: false
    properties:
      errors:
        type: error[]
        uniqueItems: true
      meta?: meta
      jsonapi?: jsonapi
      links?: links
  info:
    description: An information-only response body.
    additionalProperties: false
    properties:
      meta: meta
      links?: links
      jsonapi?: jsonapi
  meta:
    description: Where specified, a meta member can be used to include non-standard meta-information.
    type: object
  data:
    description: The document's \"primary data\" is a representation of the resource or collection of resources.
    type: resource | resource[] | nil
  resource:
    description: A resource must have both a type and id. Additional properties (see resource_post) are optional.
    type: resource_post
    properties:
      id:
  resource_post:
    description: A postable resource does not require the `id` property as it is generally assigned by the posting server.
    type: object
    additionalProperties: false
    properties:
      type:
      id?:
      attributes?: attributes
      relationships?: relationships
      links?: links
      meta?: meta
  attributes:
    description: Members of the attributes object ("attributes") represent information
      about the resource object in which it's defined.
    type: object
  links: object
  pagelinks:
    type: pagination
    properties:
      self: link
    additionalProperties: false
  link: string | linkobject
  linkobject:
    properties:
      href:
        type: uristring
        description: A string containing the link's URL.
      meta: meta
  relationships: object
  empty: nil
  pagination:
    additionalProperties: false
    properties:
      first?:
        type: uristring | nil
        description: The first page of data
      last?:
        type: uristring | nil
        description: The last page of data
      prev?:
        type: uristring | nil
        description: The previous page of data
      next?:
        type: uristring | nil
        description: The next page of data
  uristring:
  jsonapi:
    additionalProperties: false
    properties:
      version?:
      meta?: meta
  error:
    additionalProperties: false
    properties:
      id?:
        description: A unique identifier for this particular occurrence of the problem.
      links?: links
      status?:
        description: The HTTP status code applicable to this problem, expressed as a string value.
      code?:
        description: An application-specific error code, expressed as a string value.
      title?:
        description: A short, human-readable summary of the problem. It **SHOULD NOT** change from occurrence to occurrence of the problem, except for purposes of localization.
      detail?:
        description: A human-readable explanation specific to this occurrence of the problem.
      source?:
        properties:
          pointer:
            description: A JSON Pointer [RFC6901] to the associated entity in the request document [e.g. "/data" for a primary data object, or "/data/attributes/title" for a specific attribute].
          parameter:
            description: A string indicating which query parameter caused the error.
      meta?: meta
