#%RAML 1.0 Library
uses:
  types: jsonApiTypes.raml

traits:
  sortable:
    description: |
      Collection response is [sorted](http://jsonapi.org/format/#fetching-sorting) in ascending or descending(-) order.
    queryParameters:
      sort:
        description: |
          list of type.attributes to sort by. Use a `-` sign to indicate a descending sort.
        type: string
        required: false
        example: |
          sort=Location.warehouse,-Widget.qty
