#%RAML 1.0 Library

traits:
  sortable:
    description: |
      Collection response is [sorted](http://jsonapi.org/format/#fetching-sorting) in ascending or descending(-) order.
    queryParameters:
      sort?:
        description: |
          list of type.attributes to sort by. Use a `-` sign to indicate a descending sort.
        example: |
          sort=Location.warehouse,-Widget.qty
  sparse:
    description: |
      Collection response has [sparse fieldsets](http://jsonapi.org/format/#fetching-sparse-fieldsets).
    queryParameters:
      fields[<<resourcePathName>>]?:
        description: |
          Return only the listed attributes for the given type.
        example: |
          fields[Location]=warehouse,aisle&fields[Widget]=name
