#%RAML 1.0
title: Example API
baseUri: http://127.0.0.1
mediaType: application/json

/:
  get:
    responses:
      200:
        body:
          example:
            hello: world

/users:
  get:
    headers:
      Authorized:
        type: string
        enum: [yes]
    responses:
      200:
        body:
          type: array
          items: object
          example:
            - 
              firstname: Jane
              lastname: Doe
