#%RAML 1.0 DataType

type: !include vehicle.raml
properties:
  type:
    enum: [Landcraft]
  classification:
    enum: [Sedan, Station Wagons, Minivans, Sports, Luxury]
  seats:
    type: integer
    minimum: 1
    maximum: 12
  wheels:
    type: integer
    minimum: 3
    maximum: 6
  doors:
    type: integer
    minimum: 1
    maximum: 6
