#%RAML 1.0
title: Pokemon API
description: Pokemon information API
version: v1
baseUri: http://localhost:3000/{version}
mediaType: application/vnd.api+json

uses:
  jaTypes: libraries/jsonApiTypes.raml
  jaResourceTypes: libraries/jsonApiResourceTypes.raml
  jaTraits: libraries/jsonApiTraits.raml

types:
  Pokemon:
    description: Pokemon type
    type: jaTypes.resource
    properties:
      attributes: # make properties required if no PATCH defined, otherwise create two separate types
        properties:
          name?:
          generation?: number
          types?: string[]
          species?:
          abilities?: string[]
          weightKg?: number

/pokemon:
  type:
    jaResourceTypes.collection:
      dataType: Pokemon
      exampleCollection: !include examples/PokemonCollectionExample.json
      exampleItem: !include examples/PokemonItemExample.json
  get:
    is: [ jaTraits.sortable ]

  /{id}:
    type:
      jaResourceTypes.item:
        dataType: Pokemon
        # dataTypeEditable: Pokemon
        exampleItem: !include examples/PokemonItemExample.json
    # patch:
