#%RAML 1.0
title: Pokemon API
description: Pokemon information API
version: v1
baseUri: http://localhost:3000/{version}
mediaType: application/vnd.api+json

uses:
  jaTypes: libraries/jsonApiTypes.raml
  jaResourceTypes: libraries/jsonApiResourceTypes.raml
  jaTraits: libraries/jsonApiTraits.raml

types:
  PokemonAttrs:
    displayName: PokemonAttrs
    description: Pokemon attributes without any meta, type, id, etc.
    type: jaTypes.attributes
    properties:
      name?: string
      generation?: number
      types?: string[]
      species?: string
      abilities?: string[]
      weightKg?: number
  Pokemon:
    type: jaTypes.resource
    description: Pokemon type
    properties:
      attributes:
        type: PokemonAttrs

/pokemon:
  type:
    jaResourceTypes.collection:
      dataType: Pokemon
      exampleCollection: !include examples/PokemonCollectionExample.json
      exampleItem: !include examples/PokemonItemExample.json
  get:
    is: [ jaTraits.sortable ]

  /{id}:
    type:
      jaResourceTypes.item:
        dataType: Pokemon
        exampleItem: !include examples/PokemonItemExample.json
