#%RAML 1.0 Library

uses:
  tra: traits.lib.raml
  typ: types.lib.raml


resourceTypes:
  base:
    get:
      displayName: GET <<resourcePath>>
      responses:
        200:
          body:
            application/json:
              type: typ.Get<<resourcePathName | !uppercamelcase>>Response
  read-only-collection:
    type: base
    get:
      displayName: GET <<resourcePath>>
      is: [tra.pageable]
  collection:
    type: read-only-collection
    put?:
      displayName: PUT <<resourcePath>>
      body:
        type: typ.Post<<resourcePathName | !uppercamelcase>>Request
    post:
      displayName: POST <<resourcePath>>
      body:
        type: typ.Post<<resourcePathName | !uppercamelcase>>Request
      responses:
        201:
          description: Created!
          headers:
            Location:
              description: uri of new resource
              type: string
              required: true
  controller:
    post:
      displayName: POST <<resourcePath>>
      responses:
        204:
          description: Done!
  member:
    type: base
    put?:
      displayName: PUT <<resourcePath>>
      body:
        type: typ.Put<<resourcePathName | !uppercamelcase>>Request
      responses:
        204:
          description: Modified
    patch?:
      displayName: PATCH <<resourcePath>>
      body:
        type: typ.Patch<<resourcePathName | !uppercamelcase>>Request
    delete?:
      displayName: DELETE <<resourcePath>>
      responses:
        204:
          description: Delete
