#%RAML 1.0 Library

uses:
  ano: annotations.lib.raml

types:
  ResourceLink:
    displayName: Resource Link
    description: Item Resource Link type
    properties:
      href: string
      rel:
        enum: [self, next, prev]
      method?:
        default: get

  ImageLink:
    displayName: Image Link
    description: Item Image Link type
    properties:
      href: string
      rel:
        enum: [SmallImage, MediumImage, LargeImage]

  Item:
    description: Store item
    type: object
    minProperties: 1
    properties:
      id:
        type: string
        minLength: 1
        maxLength: 128
      type?: string
      name: string
      summary?: string
      brand?: string
      links: (ResourceLink | ImageLink)[]
      /^note\d+$/: string
    facets:
      storeItem?: boolean

  Sku:
    displayName: SKU
    description: Item SKU
    type: Item
    storeItem: true
    properties:
      price: number
      sku: string
      stockQuantity: integer

  GetItemsResponse:
    displayName: GET Items response
    description: Response to GET Items request
    properties:
      links: ResourceLink[]
      collection:
        properties:
          size:
            type: integer
            minimum: 1
          items: Item[]
    example:
      links:
        - href: https://avocado-brick.hi/api/v1/items?pageIndex=30&pageSize=10
          rel: next
        - href: https://avocado-brick.hi/api/v1/items?pageIndex=10&pageSize=10
          rel: prev
        - href: https://avocado-brick.hi/api/v1/items?pageIndex=20&pageSize=10
          rel: self
      collection:
        size: 2
        items:
          - id: B003Y60XCC
            type: Chemical Hair Dyes
            name: L'Oreal Oreor 30 Volume Creme Developer
            brand: L'Oreal Paris
            links:
              - href: https://avocado-brick.hi/api/v1/items/B003Y60XCC
                rel: self
              - href: http://avocado-brick.hi/images/I/41MWX6KNAuL._SL75_.jpg
                rel: SmallImage
          - id: B0042YK9F6
            type: Bath Pearls & Flakes
            name: Pearlcium Pearl Powder
            brand: TheraPure Health Essentials
            links:
              - href: https://avocado-brick.hi/api/v1/items/B0042YK9F6
                rel: self
              - href: http://avocado-brick.hi/images/I/316RsE4g09L._SL75_.jpg
                rel: SmallImage

  GetItemResponse:
    displayName: Get Item response
    description: Response to GET Item request
    type: Item
    storeItem: false
    properties:
      skus:
        properties:
          size:
            type: integer
            minimum: 1
          items: Sku[]
    example:
      links:
        - href: https://localhost:8082/omni-channel-api/v1.0/items/B0044D30Z6
          rel: self
      id: B0044D30Z6
      type: Chemical Hair Dyes
      name: Garnier HerbaShine Color Creme with Bamboo Extract
      brand: Garnier
      skus:
        size: 2
        items:
          - id: B007JTF8PX
            name: Garnier Herbashine Haircolor, 630 Light Golden Brown
            summary: Only 10 minutes
            price: 15.98
            sku: B007JTF8PX
            stockQuantity: 3
            links:
              - href: https://localhost:8082/omni-channel-api/v1.0/items/B007JTF8PX
                rel: self
              - href: http://avocado-brick.hi/images/I/ASKG67GHJ._SL75_.jpg
                rel: SmallImage
          - id: B005JXGCFE
            name: Garnier HerbaShine Color Creme, with Bamboo Extract, Dark Natural, Brown 400
            summary: Used For Hair Color
            price: 12.98
            sku: B005JXGCFE
            stockQuantity: 3
            links:
              - href: https://localhost:8082/omni-channel-api/v1.0/items/B005JXGCFE
                rel: self
              - href: http://avocado-brick.hi/images/I/847gjx12._SL75_.jpg
                rel: SmallImage

  GetMyWishListResponse:
    displayName: GET My Wish List response
    description: GET requests response of My With List endpoint
    type: GetItemsResponse

  PostMyWishListRequest:
    displayName: POST My Wish List response
    description: POST requests response of My With List endpoint
    properties:
      sku: string
    example:
      displayName: Simple response
      description: POST My Wish List response example
      strict: false
      value:
        sku: B004GW14E4


  GetMyBasketResponse:
    displayName: GET My Basket response
    description: GET requests response of My Basket endpoint
    properties:
      links: ResourceLink[]
      items:
        type: array
        items:
          type: Sku
          properties:
            quantity: integer
    example:
      links:
        - href: https://localhost:8082/omni-channel-api/v1.0/items/B0044D30Z6
          rel: self
      items:
        - id: B007JTF8PX
          name: Garnier Herbashine Haircolor, 630 Light Golden Brown
          summary: Only 10 minutes
          price: 15.98
          sku: B007JTF8PX
          stockQuantity: 3
          links:
            - href: https://localhost:8082/omni-channel-api/v1.0/items/B007JTF8PX
              rel: self
            - href: http://avocado-brick.hi/images/I/ASKG67GHJ._SL75_.jpg
              rel: SmallImage
          quantity: 5
        - id: B005JXGCFE
          name: Garnier HerbaShine Color Creme, with Bamboo Extract, Dark Natural, Brown 400
          summary: Used For Hair Color
          price: 12.98
          sku: B005JXGCFE
          stockQuantity: 3
          links:
            - href: https://localhost:8082/omni-channel-api/v1.0/items/B005JXGCFE
              rel: self
            - href: http://avocado-brick.hi/images/I/847gjx12._SL75_.jpg
              rel: SmallImage
          quantity: 1

  PostMyBasketRequest:
    displayName: POST My Basket request
    description: POST requests of My Basket endpoint
    properties:
      sku:
        type: string
        minLength: 1
        maxLength: 128
      quantity: integer
      price: number
    example:
      sku: B000538ER
      quantity: 2
      price: 10.99

  PostCheckoutRequest:
    displayName: POST Checkout request
    description: POST requests of Checkout endpoint
    properties:
      pickupLocation: string
      items:
        type: array
        items:
          properties:
            sku: string
            price: number
            quantity: integer
    example:
      pickupLocation: Dublin
      items:
        - sku: B007JTF8PX
          price: 10.99
          quantity: 1
        - sku: B000538ER
          price: 5.99
          quantity: 3

  GetMyProfileResponse:
    displayName: GET My Profile response
    description: Response to GET My Profile request
    properties:
      firstName: string
      lastName: string
      notificationPreferences:
        type: array
        items:
          type: string
          enum: [email, mobilePush, sms]
    example:
      firstName: Nial
      lastName: Darbey
      notificationPreferences:
        - sms
        - mobilePush

  GetBrandsResponse:
    displayName: GET Brands response
    description: Response to GET Brands request
    properties:
      links: ResourceLink[]
      items: string[]
    example:
      links:
        - href: https://avocado-brick.hi/api/v1/brands/dsf23
          rel: self
      items:
        - Jerome Russell
        - Now Foods

  GetCategoriesResponse:
    displayName: GET Categories response
    description: Response to GET Categories request
    properties:
      links: ResourceLink[]
      items: string[]
    example:
      links:
        - href: https://avocado-brick.hi/api/v1/categories/xx22
          rel: self
      items:
        - Soaps
        - Perfumes

  GetMyOrdersResponse:
    displayName: GET My Orders response
    description: Response to GET My Orders request
    properties:
      links: ResourceLink[]
      orders:
        type: array
        items:
          properties:
            date:
              type: datetime
              format: rfc3339
            items:
              type: array
              items:
                type: Sku
                properties:
                  quantity: integer

  GetRecommendationsResponse:
    displayName: GET Recommendations response
    description: Response to GET Recommendations request
    type: GetItemsResponse

  GetTrendingItemsResponse:
    displayName: GET Trending Items response
    description: Response to GET Trending Items request
    type: GetItemsResponse

  GetPromotionsResponse:
    displayName: GET Promotions response
    description: Response to GET Promotions request
    type: GetItemsResponse

  GetReviewsResponse:
    displayName: GET Reviews response
    description: Response to GET Reviews request
    properties:
      collection:
        properties:
          size: integer
          items:
            type: array
            items:
              properties:
                user: string
                review: string
